### ISSUE TITLE
Difficulty

### ISSUE THREAD

**Issue by Shamsco** [Capstone-Elementals/Elementals#13]
Difficulty not working properly, Sometimes Crashes occur, sometimes runs smoothly....

**Comment by Alhwirif** [comment]
found something that might be the cause of the problem. it seem that the cause is unity cloud timing out when ever we run the game.

took this from unity log file, and for some reason this report shows sometimes in the log.

Request timed out while processing request "https://public-cdn.cloud.unity3d.com/config/production"
